# User Experience Analytics

In [2]:
import os
import sys
# Add the 'scripts' directory to the Python path for module imports
sys.path.append(os.path.abspath(os.path.join('..', 'scripts')))

In [3]:
# Import necessary libraries
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np

In [5]:
# Load the cleaned xdr data into a DataFrame
data = pd.read_csv('../data/xdr_cleaned.csv', index_col=0)

In [6]:
data.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,...,Other UL (Bytes),Total UL (Bytes),Total DL (Bytes),Social Media Total (Bytes),Google Total (Bytes),Email Total (Bytes),Youtube Total (Bytes),Netflix Total (Bytes),Gaming Total (Bytes),Other Total (Bytes)
0,1.311448e+19,2019-04-04 12:01:00,770.0,4/25/2019 14:35,662.0,241983.25,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,...,8814393.0,36749741.0,308879636.0,1570185.0,2905912.0,3544322.25,18355943.0,17855187.0,2.924265e+08,180558843.0
1,1.311448e+19,2019-04-09 13:04:00,235.0,4/25/2019 8:15,606.0,241983.25,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,...,15055145.0,53800391.0,653384965.0,1933278.0,4414096.0,937385.00,39359124.0,35565545.0,6.099208e+08,541959383.0
2,1.311448e+19,2019-04-09 17:42:00,49.0,4/25/2019 11:58,652.0,241983.25,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,...,4215763.0,27883638.0,279807335.0,1726277.0,10229119.0,3363124.00,34425237.0,23751202.0,2.304179e+08,414908351.0
3,1.311448e+19,2019-04-10 00:31:00,486.0,4/25/2019 7:36,171.0,241983.25,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,...,12797283.0,43324218.0,834328852.0,657493.0,11811761.0,2070983.00,36534765.0,15096133.5,8.103879e+08,761837216.0
4,1.311448e+19,2019-04-12 20:10:00,565.0,4/25/2019 10:40,947.0,241983.25,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,...,13910322.0,38542814.0,569138589.0,912788.0,7748843.0,2110349.00,34222253.0,18226068.5,5.312370e+08,564619822.0